//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outliner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OutlinerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OutlinerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Outliner.OutlinerResources", typeof(OutlinerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap activelayer {
            get {
                object obj = ResourceManager.GetObject("activelayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap add_button {
            get {
                object obj = ResourceManager.GetObject("add_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap add_button_disabled {
            get {
                object obj = ResourceManager.GetObject("add_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap advrename {
            get {
                object obj = ResourceManager.GetObject("advrename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap boxmode_button {
            get {
                object obj = ResourceManager.GetObject("boxmode_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap boxmode_button_disabled {
            get {
                object obj = ResourceManager.GetObject("boxmode_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap case_sensitive {
            get {
                object obj = ResourceManager.GetObject("case_sensitive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap childnodes {
            get {
                object obj = ResourceManager.GetObject("childnodes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Selection To.
        /// </summary>
        public static string ContextMenuAddTo {
            get {
                return ResourceManager.GetString("ContextMenuAddTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Rename.
        /// </summary>
        public static string ContextMenuAdvRename {
            get {
                return ResourceManager.GetString("ContextMenuAdvRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backface Cull.
        /// </summary>
        public static string ContextMenuBackfaceCull {
            get {
                return ResourceManager.GetString("ContextMenuBackfaceCull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display As Box.
        /// </summary>
        public static string ContextMenuBoxMode {
            get {
                return ResourceManager.GetString("ContextMenuBoxMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Layer.
        /// </summary>
        public static string ContextMenuCreateNewLayer {
            get {
                return ResourceManager.GetString("ContextMenuCreateNewLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ContextMenuDelete {
            get {
                return ResourceManager.GetString("ContextMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bounding Box.
        /// </summary>
        public static string ContextMenuDisplayBoundingBox {
            get {
                return ResourceManager.GetString("ContextMenuDisplayBoundingBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Settings.
        /// </summary>
        public static string ContextMenuDisplayProperties {
            get {
                return ResourceManager.GetString("ContextMenuDisplayProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Through.
        /// </summary>
        public static string ContextMenuDisplaySeeThrough {
            get {
                return ResourceManager.GetString("ContextMenuDisplaySeeThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaded.
        /// </summary>
        public static string ContextMenuDisplayShaded {
            get {
                return ResourceManager.GetString("ContextMenuDisplayShaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajectory.
        /// </summary>
        public static string ContextMenuDisplayTrajectory {
            get {
                return ResourceManager.GetString("ContextMenuDisplayTrajectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewport.
        /// </summary>
        public static string ContextMenuDisplayViewport {
            get {
                return ResourceManager.GetString("ContextMenuDisplayViewport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireframe.
        /// </summary>
        public static string ContextMenuDisplayWireframe {
            get {
                return ResourceManager.GetString("ContextMenuDisplayWireframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit material in ....
        /// </summary>
        public static string ContextMenuEditMaterial {
            get {
                return ResourceManager.GetString("ContextMenuEditMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Slate.
        /// </summary>
        public static string ContextMenuEditMaterialInCurrentSlate {
            get {
                return ResourceManager.GetString("ContextMenuEditMaterialInCurrentSlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Slate.
        /// </summary>
        public static string ContextMenuEditMaterialInNewSlate {
            get {
                return ResourceManager.GetString("ContextMenuEditMaterialInNewSlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze Selection.
        /// </summary>
        public static string ContextMenuFreeze {
            get {
                return ResourceManager.GetString("ContextMenuFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Selection.
        /// </summary>
        public static string ContextMenuHide {
            get {
                return ResourceManager.GetString("ContextMenuHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherit From Layer.
        /// </summary>
        public static string ContextMenuInheritFromLayer {
            get {
                return ResourceManager.GetString("ContextMenuInheritFromLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set All Objects Inherit From Layer.
        /// </summary>
        public static string ContextMenuInheritFromLayerAll {
            get {
                return ResourceManager.GetString("ContextMenuInheritFromLayerAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer Properties.
        /// </summary>
        public static string ContextMenuLayerProperties {
            get {
                return ResourceManager.GetString("ContextMenuLayerProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Container.
        /// </summary>
        public static string ContextMenuNewContainer {
            get {
                return ResourceManager.GetString("ContextMenuNewContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Group.
        /// </summary>
        public static string ContextMenuNewGroup {
            get {
                return ResourceManager.GetString("ContextMenuNewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Layer.
        /// </summary>
        public static string ContextMenuNewLayer {
            get {
                return ResourceManager.GetString("ContextMenuNewLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Properties.
        /// </summary>
        public static string ContextMenuObjectProperties {
            get {
                return ResourceManager.GetString("ContextMenuObjectProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string ContextMenuRename {
            get {
                return ResourceManager.GetString("ContextMenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render.
        /// </summary>
        public static string ContextMenuRender {
            get {
                return ResourceManager.GetString("ContextMenuRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast Shadows.
        /// </summary>
        public static string ContextMenuRenderCastShadows {
            get {
                return ResourceManager.GetString("ContextMenuRenderCastShadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render Settings.
        /// </summary>
        public static string ContextMenuRenderProperties {
            get {
                return ResourceManager.GetString("ContextMenuRenderProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Shadows.
        /// </summary>
        public static string ContextMenuRenderReceiveShadows {
            get {
                return ResourceManager.GetString("ContextMenuRenderReceiveShadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible To Camera.
        /// </summary>
        public static string ContextMenuRenderVisToCam {
            get {
                return ResourceManager.GetString("ContextMenuRenderVisToCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible To Reflections/Refractions.
        /// </summary>
        public static string ContextMenuRenderVisToRefl {
            get {
                return ResourceManager.GetString("ContextMenuRenderVisToRefl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Childnodes.
        /// </summary>
        public static string ContextMenuSelectChildnodes {
            get {
                return ResourceManager.GetString("ContextMenuSelectChildnodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Active Layer.
        /// </summary>
        public static string ContextMenuSetActiveLayer {
            get {
                return ResourceManager.GetString("ContextMenuSetActiveLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Material In Viewport.
        /// </summary>
        public static string ContextMenuShowInVpt {
            get {
                return ResourceManager.GetString("ContextMenuShowInVpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfreeze Selection.
        /// </summary>
        public static string ContextMenuUnfreeze {
            get {
                return ResourceManager.GetString("ContextMenuUnfreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup.
        /// </summary>
        public static string ContextMenuUngroup {
            get {
                return ResourceManager.GetString("ContextMenuUngroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhide Selection.
        /// </summary>
        public static string ContextMenuUnhide {
            get {
                return ResourceManager.GetString("ContextMenuUnhide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlink.
        /// </summary>
        public static string ContextMenuUnlink {
            get {
                return ResourceManager.GetString("ContextMenuUnlink", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap filter {
            get {
                object obj = ResourceManager.GetObject("filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap filter_disabled {
            get {
                object obj = ResourceManager.GetObject("filter_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap flat_object_list_mode {
            get {
                object obj = ResourceManager.GetObject("flat_object_list_mode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap freeze {
            get {
                object obj = ResourceManager.GetObject("freeze", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap freeze_button {
            get {
                object obj = ResourceManager.GetObject("freeze_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap freeze_button_disabled {
            get {
                object obj = ResourceManager.GetObject("freeze_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hide {
            get {
                object obj = ResourceManager.GetObject("hide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hide_button {
            get {
                object obj = ResourceManager.GetObject("hide_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hide_button_disabled {
            get {
                object obj = ResourceManager.GetObject("hide_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hierarchy_mode {
            get {
                object obj = ResourceManager.GetObject("hierarchy_mode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer names must be unique (case-insensitive).
        /// </summary>
        public static string InvalidLayerNameMessage {
            get {
                return ResourceManager.GetString("InvalidLayerNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid layer name.
        /// </summary>
        public static string InvalidLayerNameTitle {
            get {
                return ResourceManager.GetString("InvalidLayerNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material names must be unique (case-insensitive).
        /// </summary>
        public static string InvalidMaterialNameMessage {
            get {
                return ResourceManager.GetString("InvalidMaterialNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid material name.
        /// </summary>
        public static string InvalidMaterialNameTitle {
            get {
                return ResourceManager.GetString("InvalidMaterialNameTitle", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap layer {
            get {
                object obj = ResourceManager.GetObject("layer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap layer_mode {
            get {
                object obj = ResourceManager.GetObject("layer_mode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap material_mode {
            get {
                object obj = ResourceManager.GetObject("material_mode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap new_selectionset {
            get {
                object obj = ResourceManager.GetObject("new_selectionset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap newcontainer {
            get {
                object obj = ResourceManager.GetObject("newcontainer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap newgroup {
            get {
                object obj = ResourceManager.GetObject("newgroup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap newlayer {
            get {
                object obj = ResourceManager.GetObject("newlayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap properties {
            get {
                object obj = ResourceManager.GetObject("properties", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap rename {
            get {
                object obj = ResourceManager.GetObject("rename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap selection_set_mode {
            get {
                object obj = ResourceManager.GetObject("selection_set_mode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap slate_mat_editor {
            get {
                object obj = ResourceManager.GetObject("slate_mat_editor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap slate_mat_editor_new {
            get {
                object obj = ResourceManager.GetObject("slate_mat_editor_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap sort_alphabetical {
            get {
                object obj = ResourceManager.GetObject("sort_alphabetical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap sort_chronological {
            get {
                object obj = ResourceManager.GetObject("sort_chronological", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap sort_layer {
            get {
                object obj = ResourceManager.GetObject("sort_layer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap sort_material {
            get {
                object obj = ResourceManager.GetObject("sort_material", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap sort_type {
            get {
                object obj = ResourceManager.GetObject("sort_type", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap sort_visibility {
            get {
                object obj = ResourceManager.GetObject("sort_visibility", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ungroup {
            get {
                object obj = ResourceManager.GetObject("ungroup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap unlink {
            get {
                object obj = ResourceManager.GetObject("unlink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window {
            get {
                object obj = ResourceManager.GetObject("window", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_new {
            get {
                object obj = ResourceManager.GetObject("window_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_options {
            get {
                object obj = ResourceManager.GetObject("window_options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_split_hor {
            get {
                object obj = ResourceManager.GetObject("window_split_hor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_split_ver {
            get {
                object obj = ResourceManager.GetObject("window_split_ver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
